/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import dados.AppDao;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Junior
 */
public class AlterarMedico extends javax.swing.JFrame {

    /**
     * Creates new form AlterarMedico
     */
    public AlterarMedico() {
        initComponents();
    }
    
    public AlterarMedico(String nome, String senha, String crm) {
        initComponents();
        
        txtNomeMedico.setText(nome);
        txtSenhaMedico.setText(senha);
        txtCrmMedico.setText(crm);
        
        txtCrmMedico.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeMedico = new javax.swing.JLabel();
        txtSenhaMedico = new javax.swing.JTextField();
        lblSenhaMedico = new javax.swing.JLabel();
        lblSenhaMedico1 = new javax.swing.JLabel();
        txtCrmMedico = new javax.swing.JFormattedTextField();
        txtNomeMedico = new javax.swing.JTextField();
        bntAlterarMedico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Dados dos Médicos - ADS Consultas");
        getContentPane().setLayout(null);

        lblNomeMedico.setText("Nome:");
        lblNomeMedico.setToolTipText("");
        getContentPane().add(lblNomeMedico);
        lblNomeMedico.setBounds(40, 60, 50, 30);

        txtSenhaMedico.setToolTipText("");
        txtSenhaMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(txtSenhaMedico);
        txtSenhaMedico.setBounds(90, 110, 310, 30);

        lblSenhaMedico.setText("Senha:");
        lblSenhaMedico.setToolTipText("");
        getContentPane().add(lblSenhaMedico);
        lblSenhaMedico.setBounds(40, 110, 50, 30);

        lblSenhaMedico1.setText("CRM:");
        lblSenhaMedico1.setToolTipText("");
        getContentPane().add(lblSenhaMedico1);
        lblSenhaMedico1.setBounds(40, 160, 50, 30);

        try {
            txtCrmMedico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######/UU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCrmMedico.setToolTipText("");
        txtCrmMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCrmMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCrmMedico);
        txtCrmMedico.setBounds(90, 160, 150, 30);

        txtNomeMedico.setToolTipText("");
        txtNomeMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeMedico);
        txtNomeMedico.setBounds(90, 60, 310, 30);

        bntAlterarMedico.setText("Altetar");
        bntAlterarMedico.setToolTipText("");
        bntAlterarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAlterarMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(bntAlterarMedico);
        bntAlterarMedico.setBounds(170, 223, 72, 30);

        setSize(new java.awt.Dimension(462, 295));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSenhaMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaMedicoActionPerformed

    private void txtCrmMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCrmMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCrmMedicoActionPerformed

    private void txtNomeMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeMedicoActionPerformed

    private void bntAlterarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAlterarMedicoActionPerformed
        String nome, senha;
        
        nome = txtNomeMedico.getText();
        senha = txtSenhaMedico.getText();
        
        try{
            new AppDao().alterarMedico(nome, senha);
            JOptionPane.showMessageDialog(null, "Médico alterado com sucesso.");
        }catch(ClassNotFoundException ex){
            JOptionPane.showMessageDialog(null, "Erro ao tentar localizar o Driver.");
        }catch(SQLException ex){
            if (ex.getMessage().contains("Duplicate entry")) {
                JOptionPane.showMessageDialog(null, "Médico já cadastrado");
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao tentar localizar o Banco de Dados." + ex.getMessage());
            }
        }
    }//GEN-LAST:event_bntAlterarMedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAlterarMedico;
    private javax.swing.JLabel lblNomeMedico;
    private javax.swing.JLabel lblSenhaMedico;
    private javax.swing.JLabel lblSenhaMedico1;
    private javax.swing.JFormattedTextField txtCrmMedico;
    private javax.swing.JTextField txtNomeMedico;
    private javax.swing.JTextField txtSenhaMedico;
    // End of variables declaration//GEN-END:variables
}
