/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import dados.AppDao;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Junior
 */
public class AlterarPaciente extends javax.swing.JFrame {

    /**
     * Creates new form AlterarPaciente
     */
    public AlterarPaciente() {
        initComponents();
    }

    public AlterarPaciente(String nome, String cpf, String tel, String endereco, String cep, String bairro, String complemento, String numero) {
        initComponents();

        txtNomePaciente.setText(nome);
        txtCpfPaciente.setText(cpf);
        txtTelPaciente.setText(tel);
        txtEndPaciente.setText(endereco);
        txtCepPaciente.setText(cep);
        txtBairroPaciente.setText(bairro);
        txtCompPaciente.setText(complemento);
        txtNumPaciente.setText(numero);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomePaciente = new javax.swing.JLabel();
        txtNomePaciente = new javax.swing.JTextField();
        lblCpfPaciente = new javax.swing.JLabel();
        lblTelPaciente = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblCepPaciente = new javax.swing.JLabel();
        lblTituloFormulario = new javax.swing.JLabel();
        lblEndPaciente = new javax.swing.JLabel();
        txtEndPaciente = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblBairroPaciente = new javax.swing.JLabel();
        txtBairroPaciente = new javax.swing.JTextField();
        lblNumPaciente = new javax.swing.JLabel();
        txtNumPaciente = new javax.swing.JTextField();
        lblCompPaciente = new javax.swing.JLabel();
        txtCompPaciente = new javax.swing.JTextField();
        btnCadastrarPaciente = new javax.swing.JButton();
        txtTelPaciente = new javax.swing.JFormattedTextField();
        txtCpfPaciente = new javax.swing.JFormattedTextField();
        txtCepPaciente = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Paciente - ADS Consultas");
        getContentPane().setLayout(null);

        lblNomePaciente.setText("Nome: ");
        getContentPane().add(lblNomePaciente);
        lblNomePaciente.setBounds(70, 60, 50, 20);

        txtNomePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomePacienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomePaciente);
        txtNomePaciente.setBounds(70, 80, 340, 30);

        lblCpfPaciente.setText("CPF:");
        getContentPane().add(lblCpfPaciente);
        lblCpfPaciente.setBounds(500, 60, 40, 20);

        lblTelPaciente.setText("Telefone:");
        getContentPane().add(lblTelPaciente);
        lblTelPaciente.setBounds(70, 120, 70, 20);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 50, 780, 10);

        lblCepPaciente.setText("CEP:");
        getContentPane().add(lblCepPaciente);
        lblCepPaciente.setBounds(500, 200, 40, 20);

        lblTituloFormulario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloFormulario.setText("Dados do Paciente");
        getContentPane().add(lblTituloFormulario);
        lblTituloFormulario.setBounds(30, 10, 160, 30);

        lblEndPaciente.setText("Endereço:");
        getContentPane().add(lblEndPaciente);
        lblEndPaciente.setBounds(70, 200, 60, 20);

        txtEndPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEndPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtEndPaciente);
        txtEndPaciente.setBounds(70, 220, 340, 30);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 190, 780, 10);

        lblBairroPaciente.setText("Bairro:");
        getContentPane().add(lblBairroPaciente);
        lblBairroPaciente.setBounds(70, 270, 50, 20);

        txtBairroPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtBairroPaciente);
        txtBairroPaciente.setBounds(70, 290, 220, 30);

        lblNumPaciente.setText("Numero:");
        getContentPane().add(lblNumPaciente);
        lblNumPaciente.setBounds(600, 270, 60, 20);

        txtNumPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumPaciente);
        txtNumPaciente.setBounds(600, 290, 90, 30);

        lblCompPaciente.setText("Complemento:");
        getContentPane().add(lblCompPaciente);
        lblCompPaciente.setBounds(350, 270, 90, 20);

        txtCompPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtCompPaciente);
        txtCompPaciente.setBounds(350, 290, 200, 30);

        btnCadastrarPaciente.setText("Alterar");
        btnCadastrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrarPaciente);
        btnCadastrarPaciente.setBounds(310, 360, 110, 30);

        try {
            txtTelPaciente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelPaciente);
        txtTelPaciente.setBounds(70, 142, 250, 30);

        try {
            txtCpfPaciente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtCpfPaciente);
        txtCpfPaciente.setBounds(500, 82, 170, 30);

        try {
            txtCepPaciente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtCepPaciente);
        txtCepPaciente.setBounds(500, 220, 170, 30);

        setSize(new java.awt.Dimension(753, 449));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomePacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomePacienteActionPerformed

    private void txtEndPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEndPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndPacienteActionPerformed

    private void txtBairroPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroPacienteActionPerformed

    private void txtNumPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumPacienteActionPerformed

    private void txtCompPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompPacienteActionPerformed

    private void btnCadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarPacienteActionPerformed
        String nome, endereco, cep, bairro, complemento, cpf, telefone, numero;

        nome = txtNomePaciente.getText();
        cpf = txtCpfPaciente.getText();
        telefone = txtTelPaciente.getText();
        endereco = txtEndPaciente.getText();
        cep = txtCepPaciente.getText();
        bairro = txtBairroPaciente.getText();
        complemento = txtCompPaciente.getText();
        numero = txtNumPaciente.getText();

        try {
            new AppDao().alterarPaciente(nome, cpf, telefone, endereco, cep, bairro, complemento, numero);

            JOptionPane.showMessageDialog(null, "Paciente alterado com sucesso.");

            txtNomePaciente.setText("");
            txtEndPaciente.setText("");
            txtCepPaciente.setText("");
            txtBairroPaciente.setText("");
            txtCompPaciente.setText("");
            txtCpfPaciente.setText("");
            txtTelPaciente.setText("");
            txtNumPaciente.setText("");
            
            dispose();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar localizar o Driver.");
        } catch (SQLException ex) {
            if (ex.getMessage().contains("Duplicate entry")) {
                JOptionPane.showMessageDialog(null, "Paciente já cadastrado");
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao tentar localizar o Banco de Dados." + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnCadastrarPacienteActionPerformed

    private void txtTelPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarPaciente;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBairroPaciente;
    private javax.swing.JLabel lblCepPaciente;
    private javax.swing.JLabel lblCompPaciente;
    private javax.swing.JLabel lblCpfPaciente;
    private javax.swing.JLabel lblEndPaciente;
    private javax.swing.JLabel lblNomePaciente;
    private javax.swing.JLabel lblNumPaciente;
    private javax.swing.JLabel lblTelPaciente;
    private javax.swing.JLabel lblTituloFormulario;
    private javax.swing.JTextField txtBairroPaciente;
    private javax.swing.JFormattedTextField txtCepPaciente;
    private javax.swing.JTextField txtCompPaciente;
    private javax.swing.JFormattedTextField txtCpfPaciente;
    private javax.swing.JTextField txtEndPaciente;
    private javax.swing.JTextField txtNomePaciente;
    private javax.swing.JTextField txtNumPaciente;
    private javax.swing.JFormattedTextField txtTelPaciente;
    // End of variables declaration//GEN-END:variables
}
