/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import dados.AppDao;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Junior
 */
public class CadastrarMedico extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarMedico
     */
    public CadastrarMedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeMedico = new javax.swing.JLabel();
        txtSenhaMedico = new javax.swing.JTextField();
        lblSenhaMedico = new javax.swing.JLabel();
        lblSenhaMedico1 = new javax.swing.JLabel();
        txtCrmMedico = new javax.swing.JFormattedTextField();
        txtNomeMedico = new javax.swing.JTextField();
        btnCadastrarMedico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastra Médico - ADS Consultas");
        getContentPane().setLayout(null);

        lblNomeMedico.setText("Nome:");
        getContentPane().add(lblNomeMedico);
        lblNomeMedico.setBounds(40, 60, 50, 30);

        txtSenhaMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(txtSenhaMedico);
        txtSenhaMedico.setBounds(90, 110, 310, 30);

        lblSenhaMedico.setText("Senha:");
        getContentPane().add(lblSenhaMedico);
        lblSenhaMedico.setBounds(40, 110, 50, 30);

        lblSenhaMedico1.setText("CRM:");
        getContentPane().add(lblSenhaMedico1);
        lblSenhaMedico1.setBounds(40, 160, 50, 30);

        try {
            txtCrmMedico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######/UU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCrmMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCrmMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCrmMedico);
        txtCrmMedico.setBounds(90, 160, 150, 30);

        txtNomeMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeMedico);
        txtNomeMedico.setBounds(90, 60, 310, 30);

        btnCadastrarMedico.setLabel("Cadastrar");
        btnCadastrarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrarMedico);
        btnCadastrarMedico.setBounds(160, 230, 100, 30);

        setSize(new java.awt.Dimension(467, 306));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSenhaMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaMedicoActionPerformed

    private void txtCrmMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCrmMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCrmMedicoActionPerformed

    private void txtNomeMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeMedicoActionPerformed

    private void btnCadastrarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarMedicoActionPerformed
        String nome, senha,crm;

        nome = txtNomeMedico.getText();
        senha = txtSenhaMedico.getText();
        crm = txtCrmMedico.getText();

        try{
            new AppDao().cadastraMedico(nome, senha, crm);
            
            JOptionPane.showMessageDialog(null, "Médico cadastrado com sucesso!");
            
            txtNomeMedico.setText("");
            txtSenhaMedico.setText("");
            txtCrmMedico.setText("");
            dispose();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar localizar o Driver.");
        } catch (SQLException ex) {
            if (ex.getMessage().contains("Duplicate entry")) {
                JOptionPane.showMessageDialog(null, "Médico já cadastrado");
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao tentar localizar o Banco de Dados." + ex.getMessage());
            }
        }
        
    }//GEN-LAST:event_btnCadastrarMedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarMedico;
    private javax.swing.JLabel lblNomeMedico;
    private javax.swing.JLabel lblSenhaMedico;
    private javax.swing.JLabel lblSenhaMedico1;
    private javax.swing.JFormattedTextField txtCrmMedico;
    private javax.swing.JTextField txtNomeMedico;
    private javax.swing.JTextField txtSenhaMedico;
    // End of variables declaration//GEN-END:variables
}
