/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Junior
 */
public class ExibirPaciente extends javax.swing.JFrame {

    /**
     * Creates new form ExibirPaciente
     */
    public ExibirPaciente() {
        initComponents();
    }
    
    public ExibirPaciente(String nome, String cpf, String tel, String endereco, String cep, String bairro, String complemento, String numero) {
        initComponents();
        
        txtNomePaciente.setText(nome);
        txtCpfPaciente.setText(cpf);
        txtTelPaciente.setText(tel);
        txtEndPaciente.setText(endereco);
        txtCepPaciente.setText(cep);
        txtBairroPaciente.setText(bairro);
        txtCompPaciente.setText(complemento);
        txtNumPaciente.setText(numero); 
        
        txtNomePaciente.setEditable(false);
        txtEndPaciente.setEditable(false);
        txtCepPaciente.setEditable(false);
        txtBairroPaciente.setEditable(false);
        txtCompPaciente.setEditable(false);
        txtCpfPaciente.setEditable(false);
        txtTelPaciente.setEditable(false);
        txtNumPaciente.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomePaciente = new javax.swing.JLabel();
        txtNomePaciente = new javax.swing.JTextField();
        lblCpfPaciente = new javax.swing.JLabel();
        txtCpfPaciente = new javax.swing.JTextField();
        lblTelPaciente = new javax.swing.JLabel();
        txtTelPaciente = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblCepPaciente = new javax.swing.JLabel();
        txtCepPaciente = new javax.swing.JTextField();
        lblTituloFormulario = new javax.swing.JLabel();
        lblEndPaciente = new javax.swing.JLabel();
        txtEndPaciente = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblBairroPaciente = new javax.swing.JLabel();
        txtBairroPaciente = new javax.swing.JTextField();
        lblNumPaciente = new javax.swing.JLabel();
        txtNumPaciente = new javax.swing.JTextField();
        lblCompPaciente = new javax.swing.JLabel();
        txtCompPaciente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lblNomePaciente.setText("Nome: ");
        getContentPane().add(lblNomePaciente);
        lblNomePaciente.setBounds(70, 60, 50, 20);

        txtNomePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomePacienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomePaciente);
        txtNomePaciente.setBounds(70, 80, 340, 30);

        lblCpfPaciente.setText("CPF:");
        getContentPane().add(lblCpfPaciente);
        lblCpfPaciente.setBounds(500, 60, 40, 20);

        txtCpfPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtCpfPaciente);
        txtCpfPaciente.setBounds(500, 80, 190, 30);

        lblTelPaciente.setText("Telefone:");
        getContentPane().add(lblTelPaciente);
        lblTelPaciente.setBounds(70, 120, 70, 20);

        txtTelPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelPaciente);
        txtTelPaciente.setBounds(70, 140, 220, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 50, 780, 10);

        lblCepPaciente.setText("CEP:");
        getContentPane().add(lblCepPaciente);
        lblCepPaciente.setBounds(500, 200, 40, 20);

        txtCepPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCepPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtCepPaciente);
        txtCepPaciente.setBounds(500, 220, 190, 30);

        lblTituloFormulario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloFormulario.setText("Dados do Paciente");
        getContentPane().add(lblTituloFormulario);
        lblTituloFormulario.setBounds(30, 10, 160, 30);

        lblEndPaciente.setText("Endereço:");
        getContentPane().add(lblEndPaciente);
        lblEndPaciente.setBounds(70, 200, 60, 20);

        txtEndPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEndPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtEndPaciente);
        txtEndPaciente.setBounds(70, 220, 340, 30);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 190, 780, 10);

        lblBairroPaciente.setText("Bairro:");
        getContentPane().add(lblBairroPaciente);
        lblBairroPaciente.setBounds(70, 270, 50, 20);

        txtBairroPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtBairroPaciente);
        txtBairroPaciente.setBounds(70, 290, 220, 30);

        lblNumPaciente.setText("Numero:");
        getContentPane().add(lblNumPaciente);
        lblNumPaciente.setBounds(600, 270, 60, 20);

        txtNumPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumPaciente);
        txtNumPaciente.setBounds(600, 290, 90, 30);

        lblCompPaciente.setText("Complemento:");
        getContentPane().add(lblCompPaciente);
        lblCompPaciente.setBounds(350, 270, 90, 20);

        txtCompPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtCompPaciente);
        txtCompPaciente.setBounds(350, 290, 200, 30);

        setSize(new java.awt.Dimension(753, 407));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomePacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomePacienteActionPerformed

    private void txtCpfPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfPacienteActionPerformed

    private void txtTelPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelPacienteActionPerformed

    private void txtCepPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCepPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCepPacienteActionPerformed

    private void txtEndPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEndPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndPacienteActionPerformed

    private void txtBairroPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroPacienteActionPerformed

    private void txtNumPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumPacienteActionPerformed

    private void txtCompPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExibirPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExibirPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExibirPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExibirPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExibirPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBairroPaciente;
    private javax.swing.JLabel lblCepPaciente;
    private javax.swing.JLabel lblCompPaciente;
    private javax.swing.JLabel lblCpfPaciente;
    private javax.swing.JLabel lblEndPaciente;
    private javax.swing.JLabel lblNomePaciente;
    private javax.swing.JLabel lblNumPaciente;
    private javax.swing.JLabel lblTelPaciente;
    private javax.swing.JLabel lblTituloFormulario;
    private javax.swing.JTextField txtBairroPaciente;
    private javax.swing.JTextField txtCepPaciente;
    private javax.swing.JTextField txtCompPaciente;
    private javax.swing.JTextField txtCpfPaciente;
    private javax.swing.JTextField txtEndPaciente;
    private javax.swing.JTextField txtNomePaciente;
    private javax.swing.JTextField txtNumPaciente;
    private javax.swing.JTextField txtTelPaciente;
    // End of variables declaration//GEN-END:variables
}
