/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.util.Enumeration;
import javax.swing.AbstractButton;

/**
 *
 * @author Junior
 */
public class ProntuarioMedico extends javax.swing.JFrame {

    /**
     * Creates new form ProntuarioMedico
     */
    public ProntuarioMedico() {
        initComponents();
    }
    
    public ProntuarioMedico(String nome, String temp, String pressao, String localDor, String inteDor, String tipoDor, String duraDor) {
        initComponents();
        
        txtNomePaciente.setText(nome);
        txtTemp.setText(temp);
        txtPressao.setText(pressao);
        txtLocalDor.setText(localDor);
        txtInteDor.setText(inteDor);
        txtTipoDor.setText(tipoDor);
        txtDurDor.setText(duraDor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloFormulario = new javax.swing.JLabel();
        lblTemPaciente = new javax.swing.JLabel();
        lblPressaoPaciente = new javax.swing.JLabel();
        lblLocalDor = new javax.swing.JLabel();
        lblInteDor = new javax.swing.JLabel();
        lblTipoDor = new javax.swing.JLabel();
        lblDuraDor = new javax.swing.JLabel();
        txtDurDor = new javax.swing.JTextField();
        lblNomePaciente = new javax.swing.JLabel();
        txtNomePaciente = new javax.swing.JTextField();
        txtTemp = new javax.swing.JFormattedTextField();
        txtPressao = new javax.swing.JFormattedTextField();
        txtInteDor = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtProntuario = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        lblDuraDor1 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JToggleButton();
        txtTipoDor = new javax.swing.JTextField();
        txtLocalDor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prontuário Médico - ADS Consultas");
        getContentPane().setLayout(null);

        lblTituloFormulario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloFormulario.setText("Dados do Paciente");
        getContentPane().add(lblTituloFormulario);
        lblTituloFormulario.setBounds(10, 10, 160, 30);

        lblTemPaciente.setText("Temp.:");
        getContentPane().add(lblTemPaciente);
        lblTemPaciente.setBounds(30, 120, 50, 20);

        lblPressaoPaciente.setText("Pressão: ");
        getContentPane().add(lblPressaoPaciente);
        lblPressaoPaciente.setBounds(240, 120, 60, 20);

        lblLocalDor.setText("Local da dor:");
        getContentPane().add(lblLocalDor);
        lblLocalDor.setBounds(450, 120, 80, 20);

        lblInteDor.setText("Itensidade da dor (0 à 10): ");
        getContentPane().add(lblInteDor);
        lblInteDor.setBounds(30, 180, 210, 20);

        lblTipoDor.setText("Tipo de dor:");
        getContentPane().add(lblTipoDor);
        lblTipoDor.setBounds(380, 180, 80, 20);

        lblDuraDor.setText("Prontuário médico:");
        getContentPane().add(lblDuraDor);
        lblDuraDor.setBounds(30, 330, 130, 20);

        txtDurDor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDurDorActionPerformed(evt);
            }
        });
        getContentPane().add(txtDurDor);
        txtDurDor.setBounds(30, 280, 190, 30);

        lblNomePaciente.setText("Nome: ");
        getContentPane().add(lblNomePaciente);
        lblNomePaciente.setBounds(30, 60, 50, 20);

        txtNomePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomePacienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomePaciente);
        txtNomePaciente.setBounds(30, 80, 340, 30);

        try {
            txtTemp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##,#ºC")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtTemp);
        txtTemp.setBounds(30, 140, 120, 30);

        try {
            txtPressao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtPressao);
        txtPressao.setBounds(240, 140, 120, 30);

        try {
            txtInteDor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtInteDor);
        txtInteDor.setBounds(30, 210, 140, 30);

        txtProntuario.setColumns(20);
        txtProntuario.setRows(5);
        jScrollPane1.setViewportView(txtProntuario);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 360, 570, 86);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 50, 630, 10);

        lblDuraDor1.setText("Duração da dor:");
        getContentPane().add(lblDuraDor1);
        lblDuraDor1.setBounds(30, 250, 100, 20);

        btnSalvar.setText("Salvar");
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(250, 480, 100, 30);
        getContentPane().add(txtTipoDor);
        txtTipoDor.setBounds(380, 210, 170, 30);
        getContentPane().add(txtLocalDor);
        txtLocalDor.setBounds(450, 140, 100, 30);

        setSize(new java.awt.Dimension(646, 556));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDurDorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDurDorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDurDorActionPerformed

    private void txtNomePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomePacienteActionPerformed

    }//GEN-LAST:event_txtNomePacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProntuarioMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProntuarioMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProntuarioMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProntuarioMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProntuarioMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblDuraDor;
    private javax.swing.JLabel lblDuraDor1;
    private javax.swing.JLabel lblInteDor;
    private javax.swing.JLabel lblLocalDor;
    private javax.swing.JLabel lblNomePaciente;
    private javax.swing.JLabel lblPressaoPaciente;
    private javax.swing.JLabel lblTemPaciente;
    private javax.swing.JLabel lblTipoDor;
    private javax.swing.JLabel lblTituloFormulario;
    private javax.swing.JTextField txtDurDor;
    private javax.swing.JFormattedTextField txtInteDor;
    private javax.swing.JTextField txtLocalDor;
    private javax.swing.JTextField txtNomePaciente;
    private javax.swing.JFormattedTextField txtPressao;
    private javax.swing.JTextArea txtProntuario;
    private javax.swing.JFormattedTextField txtTemp;
    private javax.swing.JTextField txtTipoDor;
    // End of variables declaration//GEN-END:variables
}
