/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import dados.AppDao;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Junior
 */
public class TelaLoginRecepcionista extends javax.swing.JFrame {

    /**
     * Creates new form TelaLoginRecepcionista
     */
    public TelaLoginRecepcionista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeRecepcionista = new javax.swing.JLabel();
        txtNomeRecepcionista = new javax.swing.JTextField();
        lblSenhaRecepcionista = new javax.swing.JLabel();
        bntEntrar = new javax.swing.JButton();
        pswRecepcionista = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Recepcionista - ADS Consultas");
        getContentPane().setLayout(null);

        lblNomeRecepcionista.setText("Nome:");
        getContentPane().add(lblNomeRecepcionista);
        lblNomeRecepcionista.setBounds(60, 60, 50, 30);

        txtNomeRecepcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeRecepcionistaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeRecepcionista);
        txtNomeRecepcionista.setBounds(110, 60, 310, 30);

        lblSenhaRecepcionista.setText("Senha:");
        getContentPane().add(lblSenhaRecepcionista);
        lblSenhaRecepcionista.setBounds(60, 140, 50, 30);

        bntEntrar.setText("Entrar");
        bntEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(bntEntrar);
        bntEntrar.setBounds(190, 220, 90, 30);
        getContentPane().add(pswRecepcionista);
        pswRecepcionista.setBounds(110, 140, 310, 30);

        setSize(new java.awt.Dimension(492, 293));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeRecepcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeRecepcionistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeRecepcionistaActionPerformed

    private void bntEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEntrarActionPerformed
        String nome, senha;
        
        nome = txtNomeRecepcionista.getText();
        senha = pswRecepcionista.getText();
        
        try {
            ResultSet resultado = new AppDao().logarRecepcionista(nome, senha);
            
            if(resultado.next()){
                if(nome.equals("ADM123")){
                    String admin = "adm";
                    new Paciente(admin).setVisible(true);
                    dispose();
                }else{
                    new Paciente().setVisible(true);
                    dispose();
                }    
            }else{
                JOptionPane.showMessageDialog(null, "Usuário e/ou senha inválidos.");
            }   
        }catch(ClassNotFoundException ex){
            JOptionPane.showMessageDialog(null, "Entre em contato com o administrador e informe o erro: " + ex.getMessage());
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Entre em contato com o administrador e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_bntEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLoginRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLoginRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLoginRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLoginRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLoginRecepcionista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntEntrar;
    private javax.swing.JLabel lblNomeRecepcionista;
    private javax.swing.JLabel lblSenhaRecepcionista;
    private javax.swing.JPasswordField pswRecepcionista;
    private javax.swing.JTextField txtNomeRecepcionista;
    // End of variables declaration//GEN-END:variables
}
