/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import dados.AppDao;
import java.sql.SQLException;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;

/**
 *
 * @author gilmar.rjunior
 */
public class Triagem extends javax.swing.JFrame {

    /**
     * Creates new form Prontuario
     */
    public Triagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrTipoDor = new javax.swing.ButtonGroup();
        lblTemPaciente = new javax.swing.JLabel();
        lblPressaoPaciente = new javax.swing.JLabel();
        cmbLocDor = new javax.swing.JComboBox<>();
        lblLocalDor = new javax.swing.JLabel();
        lblInteDor = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnDor3 = new javax.swing.JRadioButton();
        btnDor1 = new javax.swing.JRadioButton();
        btnDor2 = new javax.swing.JRadioButton();
        lblTipoDor = new javax.swing.JLabel();
        lblDuraDor = new javax.swing.JLabel();
        txtDurDor = new javax.swing.JTextField();
        btnSalvarPaciente = new javax.swing.JButton();
        lblNomePaciente = new javax.swing.JLabel();
        txtNomePaciente = new javax.swing.JTextField();
        txtTemp = new javax.swing.JFormattedTextField();
        txtPressao = new javax.swing.JFormattedTextField();
        txtInteDor = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ficha do Paciente - ADS Consultas");
        setBackground(new java.awt.Color(102, 102, 102));
        setBounds(new java.awt.Rectangle(10, 10, 10, 10));
        getContentPane().setLayout(null);

        lblTemPaciente.setText("Temp.:");
        getContentPane().add(lblTemPaciente);
        lblTemPaciente.setBounds(60, 130, 50, 20);

        lblPressaoPaciente.setText("Pressão: ");
        getContentPane().add(lblPressaoPaciente);
        lblPressaoPaciente.setBounds(270, 130, 60, 20);

        cmbLocDor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Abdômem", "Cabeça", "Costela", "Braço", "Pescoço", "Mão", "Pé", "Joelho", "Costas", "Ouvido", "Articulação", "Cóccix", "Boca", "Dente", "Nariz", "Olhos", "Mandíbula" }));
        cmbLocDor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLocDorActionPerformed(evt);
            }
        });
        getContentPane().add(cmbLocDor);
        cmbLocDor.setBounds(480, 150, 150, 30);

        lblLocalDor.setText("Local da dor:");
        getContentPane().add(lblLocalDor);
        lblLocalDor.setBounds(480, 130, 80, 20);

        lblInteDor.setText("Itensidade da dor (0 à 10): ");
        getContentPane().add(lblInteDor);
        lblInteDor.setBounds(60, 190, 210, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Ficha do Paciente");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 10, 140, 30);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 50, 760, 10);

        btnGrTipoDor.add(btnDor3);
        btnDor3.setText("Pulsante");
        getContentPane().add(btnDor3);
        btnDor3.setBounds(570, 220, 80, 30);

        btnGrTipoDor.add(btnDor1);
        btnDor1.setText("Aguda");
        btnDor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDor1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDor1);
        btnDor1.setBounds(410, 220, 70, 30);

        btnGrTipoDor.add(btnDor2);
        btnDor2.setText("Contínua");
        btnDor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDor2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDor2);
        btnDor2.setBounds(480, 220, 80, 30);

        lblTipoDor.setText("Tipo de dor:");
        getContentPane().add(lblTipoDor);
        lblTipoDor.setBounds(410, 190, 80, 20);

        lblDuraDor.setText("Duração da dor:");
        getContentPane().add(lblDuraDor);
        lblDuraDor.setBounds(60, 270, 100, 20);

        txtDurDor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDurDorActionPerformed(evt);
            }
        });
        getContentPane().add(txtDurDor);
        txtDurDor.setBounds(60, 300, 190, 30);

        btnSalvarPaciente.setText("Salvar");
        btnSalvarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvarPaciente);
        btnSalvarPaciente.setBounds(310, 350, 100, 30);

        lblNomePaciente.setText("Nome: ");
        getContentPane().add(lblNomePaciente);
        lblNomePaciente.setBounds(60, 60, 50, 20);

        txtNomePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomePacienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomePaciente);
        txtNomePaciente.setBounds(60, 80, 340, 30);

        try {
            txtTemp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##,#ºC")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtTemp);
        txtTemp.setBounds(60, 150, 120, 30);

        try {
            txtPressao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtPressao);
        txtPressao.setBounds(270, 150, 120, 30);

        try {
            txtInteDor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtInteDor);
        txtInteDor.setBounds(60, 212, 140, 30);

        setSize(new java.awt.Dimension(772, 433));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDor1ActionPerformed

    private void btnDor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDor2ActionPerformed

    private void cmbLocDorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLocDorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbLocDorActionPerformed

    private void txtDurDorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDurDorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDurDorActionPerformed

    private void btnSalvarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarPacienteActionPerformed
        String nome,temp,pressao,localDor,inteDor,tipoDor = null,duraDor;
        
        nome = txtNomePaciente.getText();
        temp = txtTemp.getText();
        pressao = txtPressao.getText();
        localDor = cmbLocDor.getSelectedItem().toString();
        inteDor = txtInteDor.getText();
        for(Enumeration<AbstractButton> buttons = btnGrTipoDor.getElements(); buttons.hasMoreElements();){
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                tipoDor = button.getText();
            }
        }
        duraDor = txtDurDor.getText();
        
        new TelaLoginMedico().setVisible(true);
        
        try{
            new AppDao().cadastrarFicha(nome,temp,pressao,localDor,inteDor,tipoDor,duraDor);
            
            JOptionPane.showMessageDialog(null, "Ficha cadastrada com sucesso.");
            
            txtNomePaciente.setText("");
            txtPressao.setText("");
            txtPressao.setText("");
            txtInteDor.setText("");
            txtDurDor.setText("");
            
        }catch(ClassNotFoundException ex){
            JOptionPane.showMessageDialog(null, "Erro ao tentar localizar o Driver.");
        }catch(SQLException ex){
            if (ex.getMessage().contains("Duplicate entry")) {
                JOptionPane.showMessageDialog(null, "Ficha já cadastrado");
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao tentar localizar o Banco de Dados." + ex.getMessage());
            }
        }       
    }//GEN-LAST:event_btnSalvarPacienteActionPerformed

    private void txtNomePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomePacienteActionPerformed
        
    }//GEN-LAST:event_txtNomePacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Triagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Triagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Triagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Triagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Triagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnDor1;
    private javax.swing.JRadioButton btnDor2;
    private javax.swing.JRadioButton btnDor3;
    private javax.swing.ButtonGroup btnGrTipoDor;
    private javax.swing.JButton btnSalvarPaciente;
    private javax.swing.JComboBox<String> cmbLocDor;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblDuraDor;
    private javax.swing.JLabel lblInteDor;
    private javax.swing.JLabel lblLocalDor;
    private javax.swing.JLabel lblNomePaciente;
    private javax.swing.JLabel lblPressaoPaciente;
    private javax.swing.JLabel lblTemPaciente;
    private javax.swing.JLabel lblTipoDor;
    private javax.swing.JTextField txtDurDor;
    private javax.swing.JFormattedTextField txtInteDor;
    private javax.swing.JTextField txtNomePaciente;
    private javax.swing.JFormattedTextField txtPressao;
    private javax.swing.JFormattedTextField txtTemp;
    // End of variables declaration//GEN-END:variables
}
